### PR TITLE
add ppc64le, symlink to powerpc

### PR DESCRIPTION
**Pull request by doctaweeks**

### CODE REVIEW

**Comment by rofl0r** [comment]
could you explain why you need this? in kernel sources arch directory is no ppc64le either, and the proper toolchain triplet prefix for ppc64le is actually powerpc64le

**Comment by doctaweeks** [comment]
This is a common idiom or shorthand for powerpc64le, usually in userspace, similar to amd64/x86_64 or arm64/aarch64. It's returned by `uname -m` on Power systems.

It would be useful for projects like [enroot](https://github.com/NVIDIA/enroot), which use that userspace output to decide which arch to build. (enroot uses these headers and musl internally.)

**Comment by rofl0r** [comment]
> It would be useful for projects like enroot, which use that userspace output to decide which arch to build. (enroot uses these headers and musl internally.)

i see. enroot supports crosscompiles ? if so it would probably make more sense to use `gcc -dumpmachine` to output the target triplet

**Comment by doctaweeks** [comment]
Yes, it supports cross compiling but that's not exactly relevant. enroot builds musl and statically links against it. As a userspace application, it uses the common shorthand ppc64le for ARCH and for enroot it determines how users interact, packages are built, etc. However, that same ARCH is exported to the other libraries built and linked into enroot, like musl.

This is no different than the i386 or x86_64 symlinks that already exist. The kernel headers only have x86 as the arch but it's not uncommon for ARCH to be i386 or x86_64 coming into make.

**Pull request merged**
